"""
Django settings for licitamex project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8%li!pf&^&-ybkvhx4vm#d%pblu2urxioo_*!cc*+&+7u%*@)^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'account',
    'widget_tweaks',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'licitamex.middleware.HealthCheckMiddleware',
    'licitamex.middleware.DisableBrowserCacheMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'licitamex.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [(os.path.join(BASE_DIR, 'templates')),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

WSGI_APPLICATION = 'licitamex.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

if 'RDS_DB_NAME' in os.environ:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': os.environ['RDS_DB_NAME'],
            'USER': os.environ['RDS_USERNAME'],
            'PASSWORD': os.environ['RDS_PASSWORD'],
            'HOST': os.environ['RDS_HOSTNAME'],
            'PORT': os.environ['RDS_PORT'],
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

LOGIN_REDIRECT_URL = 'dashboard'
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'

# SMTP Server
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# PAYMENTS
PAYPAL_RECEIVER_EMAIL = 'sb-kundi2221798@business.example.com'
PAYPAL_TEST = True

DOMAIN_URL = "https://consultalicitamex.com/"
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'


if DEBUG:
    PAYPAL_CLIENT_ID = 'AbWxlPNfqE90HcRy8UXNwkg1llRdhtPS6d7k6X7vZ3iUaW4OIHsq6Neq1U1fh28bBJGEY6VRv4bYPaKo'
    PAYPAL_CLIENT_SECRET = 'EM7OhADGSL8JZjA-sa8NvtLBq-g7TX6Mi2rIAu4Tc8nPoUZWEcRMZwdgLU0fa4umvhkpn35IXxDxy2W3'
    PAYPAL_PLAN_MONTHLY_ID = "P-3PP12049MM2328251MDYIRBQ"
    PAYPAL_MODE = 'sandbox'
    PAYPAL_WEBHOOK_ID = '6XM493967V1511440'


    STRIPE_KEY= "pk_live_51JTBKjLE0Lev1MBURN83QxHSKAhryDTBXLAus1q1dMSYt89SVlM3eo5va8doPiobqWxDel3Rbp3AonV2YWafGUQP00TAcYCPQi"
    STRIPE_SECRET= "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"
    STRIPE_BASIC = "price_1JbvFDLE0Lev1MBUkO6UYo4k"


    #develop
    #STRIPE_KEY= "pk_test_51JTBKjLE0Lev1MBUh2H39chjVuLKmNiP9kH8N1u79oBnJ4GuVBhkbLECEC8dXQmd5KfqZUWwCtCLtK6f5fWMVvvn00l9XsqSKB"
    #STRIPE_SECRET= "sk_test_51JTBKjLE0Lev1MBU6xiH5khoQLWxgVfRFYf3Q2KzD8MFvyH7nQiqcjdu8AguHZSlSTjKivi234DCla9mxY7DRtxt00xaiMRas2"
    #STRIPE_BASIC = "price_1JTECJLE0Lev1MBUzpsyo8Yq"


    MJ_APIKEY_PUBLIC = "1722a360a7a830ca7443ce6d387e1836"
    MJ_APIKEY_PRIVATE = "e0a3dfefe85372b7632eb0e30e7c07b1"
