# Generated by Django 3.2.6 on 2021-08-28 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoFiltros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=250, null=True)),
                ('familia', models.CharField(max_length=250, null=True)),
                ('articulo', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('subscription_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioLicitaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licitacion_id', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('expired', models.BooleanField()),
                ('expired_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('quotation', models.CharField(max_length=300)),
                ('comments', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('entidad', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioFiltros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtro_id', models.IntegerField()),
                ('grupo', models.CharField(max_length=250, null=True)),
                ('familia', models.CharField(max_length=250, null=True)),
                ('articulo', models.CharField(max_length=250, null=True)),
                ('activado', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
