# Generated by Django 3.2.6 on 2022-03-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
