# Generated by Django 3.2.6 on 2022-04-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_group_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='payment_vendor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
