# Generated by Django 3.2.6 on 2022-04-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_group_payment_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='admin_user',
            field=models.IntegerField(default=0),
        ),
    ]
