# Generated by Django 3.2.5 on 2021-07-23 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_auto_20210506_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioLicitaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licitacion_id', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('expired', models.BooleanField()),
                ('expired_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('quotation', models.CharField(max_length=300)),
                ('comments', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
