# Generated by Django 3.2.5 on 2021-07-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_usuariolicitaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariolicitaciones',
            name='description',
            field=models.CharField(default='no hay descripcion', max_length=500),
            preserve_default=False,
        ),
    ]
