# Generated by Django 3.2.5 on 2021-07-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_usuariolicitaciones_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariolicitaciones',
            name='entidad',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
