# Generated by Django 3.2.6 on 2022-04-12 16:03

from django.db import migrations, models
import django.db.models.deletion
from ..data_tables.catalogo import aqui



class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_user_usuariopermisos_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopermisos',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.group'),
        ),
        migrations.RunPython(aqui)
    ]
