# Generated by Django 3.2.5 on 2021-08-14 22:54

from django.db import migrations, models
from ..data_tables.catalogo import probando


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_usuariolicitaciones_entidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoFiltros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=250)),
                ('familia', models.CharField(max_length=250)),
                ('articulo', models.CharField(max_length=250)),
            ],
        ),
        migrations.RunPython(probando)
    ]
