# Generated by Django 3.2.5 on 2021-08-17 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0008_catalogofiltros'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioFiltros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtro_id', models.IntegerField()),
                ('grupo', models.CharField(max_length=250)),
                ('familia', models.CharField(max_length=250)),
                ('articulo', models.CharField(max_length=250)),
                ('activado', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
