# Generated by Django 3.2.6 on 2021-08-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_usuariofiltros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogofiltros',
            name='articulo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='catalogofiltros',
            name='familia',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='catalogofiltros',
            name='grupo',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
