# Generated by Django 3.2.6 on 2021-08-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210821_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariofiltros',
            name='articulo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usuariofiltros',
            name='familia',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usuariofiltros',
            name='grupo',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
