# Generated by Django 3.2.6 on 2021-09-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_licitacioncomentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariolicitaciones',
            name='comments',
            field=models.JSONField(default='{}'),
        ),
        migrations.DeleteModel(
            name='LicitacionComentarios',
        ),
    ]
