# Generated by Django 3.2.6 on 2021-09-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20210902_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariolicitaciones',
            name='datos_comprador',
            field=models.JSONField(default='{}'),
        ),
    ]
