# Generated by Django 3.2.6 on 2021-09-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20210903_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariofiltros',
            name='articulo',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='usuariofiltros',
            name='familia',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='usuariofiltros',
            name='grupo',
            field=models.CharField(default='', max_length=250),
        ),
    ]
