# Generated by Django 3.2.6 on 2021-09-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20210906_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariolicitaciones',
            name='quotation',
            field=models.CharField(max_length=1000),
        ),
    ]
