# Generated by Django 3.2.6 on 2021-09-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_usuariolicitaciones_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariolicitaciones',
            name='quotation',
            field=models.TextField(),
        ),
    ]
