# Generated by Django 3.2.6 on 2021-09-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_userplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='plan_active',
            field=models.BooleanField(default=False),
        ),
    ]
