# Generated by Django 3.2.6 on 2021-09-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_userplan_plan_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='users',
            field=models.JSONField(default='{}'),
        ),
    ]
